---
title: "Untitled"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(fpp2)
library(ggplot2)
library(tseries)
```


```{r}
data = read.csv("C:/Users/zhang/Desktop/time/final/2000.csv", check.names = F)

beforecovid.ts <- ts(data[,2],start=c(2000,1),end=c(2022,31),freq=52)
AfterCOVID.ts <- ts(data[,2],start=c(2020,11),end=c(2022,31),freq=52)
```


```{r}
autoplot(beforecovid.ts)+
  ggtitle("Continued Claimes in US 1967-2020") +
  xlab("Year") + ylab("# of Claims") 
autoplot(AfterCOVID.ts)+
  ggtitle("Continued Claimes in US 2020-2022") +
  xlab("Year") + ylab("# of Claims") 
```

```{r}
beforecovid.train = window(beforecovid.ts, end=c(2020,1))
beforecovid.test  = window(beforecovid.ts, start=c(2020,2))

```


```{r}
plot(log(beforecovid.ts),ylab="Log # of Claims before COVID")
plot(diff(log(beforecovid.ts)),ylab="Diff of Log # of Claims before COVID")

beforecovid.diff  <- diff(log(beforecovid.ts))
logbeforecovid   <- log(beforecovid.ts)

### Not sure if this is helpful. 
plot(diff(beforecovid.diff,lag=52),ylab="Diff lag 52 of Log # of Claims before COVID")
```


```{r}
require(graphics)

acf(beforecovid.diff,lag.max=52,type = "correlation")

pacf(beforecovid.diff,lag.max=52)

#When lag=52, x-lab is too small

#Comment: The differenced log is not white noise based on acf and pacf graphs
```

```{r}
adf.test(beforecovid.diff)
kpss.test(beforecovid.diff)
#The tests show the difference to be stationary
```

#_______No Changes Before this Line


```{r}
library(forecast)

best.fit <- auto.arima(logbeforecovid)
                  
#c(2,1,3), seasonal (2,0,1) 52, drift)

```


```{r}
#best.fit2 <- Arima(logbeforecovid,order=c(2,1,3),seas=list(order=c(2,0,1),period=52),include.drift=TRUE)
```


```{r}
number.parameters <- length(best.fit$coef) + 1
n = length(logbeforecovid)
best.fit.AIC <- -2*best.fit$loglik + 2*number.parameters
best.fit.BIC <- -2*best.fit$loglik + log(n)*number.parameters
best.fit.AIC
best.fit.BIC
checkresiduals(best.fit)

```


```{r}
exp(accuracy(best.fit))
```


```{r}


```
```{r}
cafe.test <- Arima(test, model=cafe.train)
accuracy(cafe.test)
```

```{r}
h <- 52

forecast <- predict(best.fit,n.ahead=36)


plot(forecast$pred,ylab="Predicted Log of Before COVID")
lines(forecast$pred+1.96*forecast$se,lty=2,col="red")
lines(forecast$pred-1.96*forecast$se,lty=2,col="red")


plot(exp(forecast$pred),ylab="Predicted of Log of Before COVID",ylim=c(exp(14),exp(15)) )
lines(exp(forecast$pred+1.96*forecast$se),lty=2,col="red")
lines(exp(forecast$pred-1.96*forecast$se),lty=2,col="red")
print(exp(forecast$pred))
```


```{r}

Merge= ts( c(beforecovid.ts, exp(forecast$pred)), start = start(beforecovid.ts),  frequency = frequency(beforecovid.ts) )

```


```{r}
plot(Merge,ylab="Predicted Log of Before COVID",xlim=c(2022.5,2023))
lines(Merge+1.96*forecast$se,lty=2,col="red")
lines(Merge-1.96*forecast$se,lty=2,col="red")

```




####__________________
